version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: searchctl-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - searchctl-net

  opensearch:
    image: docker.io/opensearchproject/opensearch:2.11.0
    container_name: searchctl-opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9201:9200"
      - "9301:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - searchctl-net

  opensearch-dashboards:
    image: docker.io/opensearchproject/opensearch-dashboards:2.11.0
    container_name: searchctl-dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - 'DISABLE_SECURITY_DASHBOARDS_PLUGIN=true'
      - 'OPENSEARCH_SECURITY_DISABLED=true'
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - searchctl-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: searchctl-kibana
    ports:
      - "5602:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - searchctl-net

networks:
  searchctl-net:
    driver: bridge
